fix : fixing path user json
zrock-dev/980 pull request #31
Opened 2023-09-03 21:06 UTC by CatCoder36

Description: I have fixed the json user path

2023-09-03 22:07 UTC, zrock-dev requested changes
For the tests in BTreeRepositoryTest use the pathUserDataBase constant.

Hint: 
```java
String.format("%s/TestNode1.json", BTreeRepository.PATH_USER_DATA_BASE) 
```

2023-09-03 22:08 UTC, zrock-dev commented
fixes #20

2023-09-03 22:19 UTC, CatCoder36 commented on backend/src/main/java/com/fake_orgasm/users_management/repository/BTreeRepository.java
> +    private final String pathUserDataBase = "../backend/user_database";
The check style does not allow such names with uppercase only.

2023-09-03 22:33 UTC, zrock-dev commented on backend/src/main/java/com/fake_orgasm/users_management/repository/BTreeRepository.java
> +    private final String pathUserDataBase = "../backend/user_database";
it does, as an example you can check the file: src/main/java/com/fake_orgasm/generator/user_generator/UserNameGenerator.java

2023-09-03 23:51 UTC, CatCoder36 commented on backend/src/main/java/com/fake_orgasm/users_management/repository/BTreeRepository.java
> +    private final String pathUserDataBase = "../backend/user_database";
solved

2023-09-04 00:16 UTC, zrock-dev reviewed
Good job

2023-09-04 00:16 UTC, zrock-dev approved these changes

2023-09-04 00:18 UTC, merged